import {fetchAllMembers} from "../actions/user";

export const ActionTypes = {
    LOADING: "LOADING",
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    AUTHENTICATION: "AUTHENTICATION",
    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
    FETCH_ALL_MEMBERS_SUCCESS: "FETCH_ALL_MEMBERS_SUCCESS",
    FETCH_ALL_MEMBERS_LOADING: "FETCH_ALL_MEMBERS_LOADING",
    FETCH_ALL_MEMBERS_ERROR: "FETCH_ALL_MEMBERS_ERROR",
    // SET_PRODUCTS: "SET_PRODUCTS",
    // SELECTED_PRODUCT: "SELECTED_PRODUCT",
    // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    // I_JUST_REGISTERED: "I JUST REGISTERED",
    // I_DO_DISAPPEAR_MODAL: "I DO DISAPPEAR MODAL",
    // WHEN_MODAL_DO_DISAPPEAR: "WHEN MODAL DO DISAPPEAR"
}